# Generated by Django 3.1.1 on 2024-11-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates if the part is active.'),
        ),
        migrations.AlterField(
            model_name='part',
            name='alt_part_number',
            field=models.CharField(blank=True, help_text='Alternate part number.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='bin_location',
            field=models.CharField(help_text='Bin location for storage.', max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='code',
            field=models.CharField(blank=True, help_text='Code for the part.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional comments.', null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Cost of the part.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.CharField(help_text='Description of the part.', max_length=255),
        ),
        migrations.AlterField(
            model_name='part',
            name='history',
            field=models.TextField(blank=True, help_text='History of the part.', null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='last_order',
            field=models.DateField(blank=True, help_text='Date of the last order.', null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='lead_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lead time for orders.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='location',
            field=models.CharField(help_text='General location of the part.', max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='manufacturer',
            field=models.CharField(help_text='Name of the manufacturer.', max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='manufacturer_part_number',
            field=models.CharField(blank=True, help_text="Manufacturer's part number.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes.', null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='on_hand',
            field=models.IntegerField(help_text='Quantity on hand.'),
        ),
        migrations.AlterField(
            model_name='part',
            name='on_order',
            field=models.IntegerField(help_text='Quantity on order.'),
        ),
        migrations.AlterField(
            model_name='part',
            name='order_point',
            field=models.IntegerField(blank=True, help_text='Minimum quantity before reordering.', null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='order_quantity',
            field=models.IntegerField(blank=True, help_text='Quantity to order.', null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='order_status',
            field=models.CharField(blank=True, help_text='Order status.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_class',
            field=models.CharField(help_text='Class of the part.', max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, help_text='Part number of the item.', max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(blank=True, help_text='Current status of the part.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='stock',
            field=models.BooleanField(default=True, help_text='Indicates if the part is in stock.'),
        ),
        migrations.AlterField(
            model_name='part',
            name='unit_of_measure',
            field=models.CharField(help_text='Unit of measure for the part.', max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='vpart_number',
            field=models.CharField(blank=True, help_text='Vendor part number.', max_length=50, null=True),
        ),
    ]
