# Generated by Django 3.1.1 on 2024-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20241104_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='item',
        ),
        migrations.AlterField(
            model_name='part',
            name='on_hand',
            field=models.FloatField(help_text='Quantity on hand.'),
        ),
        migrations.AlterField(
            model_name='part',
            name='on_order',
            field=models.FloatField(help_text='Quantity on order.'),
        ),
        migrations.AlterField(
            model_name='part',
            name='order_point',
            field=models.FloatField(blank=True, help_text='Minimum quantity before reordering.', null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='order_quantity',
            field=models.FloatField(blank=True, help_text='Quantity to order.', null=True),
        ),
    ]
